package payout

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// fixedEIP712FixtureInputs is the committed cross-language input tuple.
// Do not change without regenerating testdata/eip712_digest_fixture.json
// and re-running the JS ethers digest test.
func fixedEIP712FixtureInputs(t *testing.T) EIP712Inputs {
	t.Helper()
	var nonce32 [32]byte
	for i := range nonce32 {
		nonce32[i] = byte(i + 1)
	}
	addr, err := CanonicalizeEIP55("0x70997970C51812dc3A010C7d01b50e0d17dc79C8")
	if err != nil {
		t.Fatalf("canon addr: %v", err)
	}
	hot, err := CanonicalizeEIP55("0x52908400098527886E0F7030069857D2E4169EE7")
	if err != nil {
		t.Fatalf("canon hot: %v", err)
	}
	return EIP712Inputs{
		ProviderID:        "test-provider-id",
		CanonicalAddr:     addr,
		Chain:             "base-mainnet",
		Nonce32:           nonce32,
		TsUtc:             1719234896,
		VerifyingContract: hot,
	}
}

// TestEIP712DigestFixture_MatchesCommitted asserts Go buildDigest
// equals the committed fixture hex. The JS test in
// testdata/eip712_js asserts ethers.TypedDataEncoder.hash matches
// the same hex — that is the cross-language linchpin against
// signature_mismatch drift.
func TestEIP712DigestFixture_MatchesCommitted(t *testing.T) {
	inputs := fixedEIP712FixtureInputs(t)
	digest, err := buildDigest(inputs)
	if err != nil {
		t.Fatalf("buildDigest: %v", err)
	}
	digestHex := "0x" + hex.EncodeToString(digest[:])

	path := filepath.Join("testdata", "eip712_digest_fixture.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var loaded struct {
		Digest string `json:"digest"`
	}
	if err := json.Unmarshal(raw, &loaded); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	if loaded.Digest != digestHex {
		t.Fatalf("Go digest %s != committed fixture %s — regenerate fixture and update JS test",
			digestHex, loaded.Digest)
	}
}

// TestEIP712DigestFixture_RoundTripJSSignature loads a signature
// produced by the JS ethers test (throwaway key only) and asserts
// VerifyEIP712 accepts it. The signature file is generated by:
//
//	node testdata/eip712_js/roundtrip_sign.mjs
//
// and committed as testdata/eip712_js/roundtrip_signature.json.
func TestEIP712DigestFixture_RoundTripJSSignature(t *testing.T) {
	path := filepath.Join("testdata", "eip712_js", "roundtrip_signature.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read roundtrip signature: %v (run: node testdata/eip712_js/roundtrip_sign.mjs)", err)
	}
	var payload struct {
		ProviderID        string `json:"providerId"`
		Address           string `json:"address"`
		Chain             string `json:"chain"`
		Nonce             string `json:"nonce"`
		TsUtc             uint64 `json:"tsUtc"`
		VerifyingContract string `json:"verifyingContract"`
		Signature         string `json:"signature"`
	}
	if err := json.Unmarshal(raw, &payload); err != nil {
		t.Fatalf("parse: %v", err)
	}
	nonce32, err := DecodeNonce32(payload.Nonce)
	if err != nil {
		t.Fatalf("nonce: %v", err)
	}
	canonAddr, err := CanonicalizeEIP55(payload.Address)
	if err != nil {
		t.Fatalf("addr: %v", err)
	}
	canonHot, err := CanonicalizeEIP55(payload.VerifyingContract)
	if err != nil {
		t.Fatalf("hot: %v", err)
	}
	inputs := EIP712Inputs{
		ProviderID:        payload.ProviderID,
		CanonicalAddr:     canonAddr,
		Chain:             payload.Chain,
		Nonce32:           nonce32,
		TsUtc:             payload.TsUtc,
		VerifyingContract: canonHot,
	}
	if _, err := VerifyEIP712(inputs, payload.Signature); err != nil {
		t.Fatalf("VerifyEIP712 rejected JS signature: %v", err)
	}
}
